### ISSUE TITLE
How to get JSON body as a params in action?

### ISSUE THREAD

**Issue by nilcolor** [lotus/controller#118]
I've create really simple Lotus app (https://gist.github.com/nilcolor/21ead88d1517e824f103). And I'd like to receive JSON data (via POST's body). But... controller receives request, responds with OK but params are empty... (not really empty - it's full Rack params hash but without data I need).
If params are posted in URL - they are readable via `params` arg. Even if action is `accept :json` btw

**Comment by joneslee85** [comment]
assigned to @brennovich

**Comment by carloslopes** [comment]
Some things appeared when @brennovich and I were investings this.

Probably @nilcolor didn't configure the `body_parsers` of his app. If he configure the `body_parsers` for json the params passed to the action will start to be available.

But some things aren't clear, and maybe @joneslee85 can help us to figure them out.
* The purpose of `body_parsers` configuration is: Define different parsers that will be used when a request is received on specific MIME types
* The purpose of `accept` is: block requests that aren't on the defined MIME types

Are this assumptions right?

ps: `accept` is currently not doing what it should, because if we configure a controller to accept only json requests, it doesn't return status code 406 for requests with different content-types

**Comment by brennovich** [comment]
Yep, as @carloslopes said @nilcolor, please make sure to uncomment this option in your `application.rb`:

<img width="962" alt="screen shot 2015-08-25 at 11 29 15 pm" src="https://cloud.githubusercontent.com/assets/379894/9484343/2d6db7b8-4b81-11e5-9c7c-6c85b404d3e9.png">

Once you get this done you'll star to get your params :)

**Comment by carloslopes** [comment]
Issue related to the accept problem: https://github.com/lotus/controller/issues/123

**Comment by nilcolor** [comment]
@brennovich @carloslopes -  thank you.

**Comment by joneslee85** [comment]
Thanks all for helping me out, this community is uber! I close thic ticket now
