### ISSUE TITLE
Whitelisting should occur even if no params are defined

### ISSUE THREAD

**Issue by davidpelaez** [lotus/controller#124]
Currently if I don't call `params` in an action the whitelisting won't be applied. The intention is clearly read in https://github.com/lotus/controller/blob/master/lib/lotus/action/params.rb#L112-L114 which makes me think this is not accidental.

However if Lotus promotes being explicit about things I'd suggest that whitelisting occurs at all times because it's weird that I can read anything if I don't have any params, but can't read anything extra once a param is defined.

So `params[:auth_token]` is visible if there are no defined params but when I define `param :amount, presence: true` the code that used to work won't work. This is surprising as opposed to the first case never working and asking me to be explicit about allowing that attribute.

**Comment by davidpelaez** [comment]
Currently if I don't call `params` in an action the whitelisting won't be applied. The intention is clearly read in https://github.com/lotus/controller/blob/master/lib/lotus/action/params.rb#L112-L114 which makes me think this is not accidental.

However if Lotus promotes being explicit about things I'd suggest that whitelisting occurs at all times because it's weird that I can read anything if I don't have any params, but can't read anything extra once a param is defined.

So `params[:auth_token]` is visible if there are no defined params but when I define `param :amount, presence: true` the code that used to work won't work. This is surprising as opposed to the first case never working and asking me to be explicit about allowing that attribute.

**Comment by jodosha** [comment]
@davidpelaez Hello and welcome. :smile: 

Whitelisting is an extra layer of security that devs may decide to enable or not (the default). If someone decides to ignore this feature, it would be weird that `params` are always empty for them.

In order to see the params, this person would be forced to whitelist them. This makes, the feature, mandatory, but we want to keep it optional.

So, if you don't care about whitelisting, you will get all the params. If you want to filter, you must be explicit about what you want.

> So `params[:auth_token]` is visible if there are no defined params but when I define `param :amount, presence: true` the code that used to work won't work.

Why is this surprising for you? This is the concept of filtering, if you don't tell the action to include `:auth_token` in the set of the allowed params, it will be rejected. If that wouldn't happen, that means whitelisting is broken.

I hope this explanation clarified the intent of the software. :smile:
