### ISSUE TITLE
Exception notifiers compatibility

### ISSUE THREAD

**Issue by jodosha** [lotus/controller#133]
Lotus::Controller [dumps exceptions](https://github.com/lotus/controller/blob/bb2f4b971adbff6ce4a2e050a08d4b1837bc848d/lib/lotus/action/throwable.rb#L132) in `rack.errors`. This is specified by [Rack SPEC](http://www.rubydoc.info/github/rack/rack/file/SPEC#The_Error_Stream).

> **`rack.errors`** | See below, the error stream.

---

> ### The Error Stream
>
> The error stream must respond to puts, write and flush.
>
> `puts` must be called with a single argument that responds to `to_s`.
> `write` must be called with a single argument that is a `String`.
> `flush` must be called without arguments and must be called in order to make the error appear for sure.
> `close` must never be called on the error stream.

---

On the other hand, the most popular exception notifier services use `rack.exception`. This isn't documented by Rack SPEC, but appears to be a de-facto standard for these services. Here's the code reference for their Ruby clients:

  * [Airbrake](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rack.rb#L60)
  * [Honeybadger](https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/rack/error_notifier.rb#L67)
  * [Bugsnag](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/rack.rb#L44)
  * [Sentry](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rack.rb#L62)

---

I can't find the reason why this is used.

**Comment by jodosha** [comment]
Linking the Twitter discussion here: https://twitter.com/jodosha/status/676708558289899520

**Comment by kyrylo** [comment]
My guessing is that someone implemented it like that and everyone else copied it. I could not find any traces of `rack.exception` in modern Rack.

**Comment by jodosha** [comment]
@kyrylo That is true for Sentry:

![screen shot 2015-12-15 at 11 37 54](https://cloud.githubusercontent.com/assets/5089/11808356/54b940b6-a320-11e5-8f68-5fda903757c7.png)

https://twitter.com/getsentry/status/676709918926245889

**Comment by weppos** [comment]
@jodosha I investigated a little bit the issue after I reported it to you, and the responses to [your tweet](https://twitter.com/jodosha/status/676708558289899520) also helped me to properly formulate an hypotesis.

At the first glance, when I discovered the issue and I compared the Lotus behavior with Bugsnag (that we use in production and that was not able to track the error), I realized we had a discrepancy:

- Lotus was using `rack.error`
- Bugsnag was using `rack.exception`

What I didn't notice, is how Lotus was using `rack.error` and what in fact `rack.error` was. After I carefully inspected the issue for the second time and you referenced me this ticket, I noticed that `rack.error` was not a simple string. Instead, per `rake` documentation, this is supposed to be a stream.

> The error stream must respond to puts, write and flush.

In other words, it's like a way for having a pointer to a logger (or another stream reader), where you can log the details of an exception when it occurs.

It's not a place where you can store the exception itself. So the next question was: why you may want to store the exception? And why none of these exception loggers are using `rack.error`.

It turns out that if you have a fairly complex application, you probably have a multi-middleware stack. And more importantly, you may have two different apps sharing the same stack, or part of it. This is our case, where we have a Lotus app mounted on a Rails router. The Lotus app independently deals with a specific subset of routes but it shares the middleware chain with the main Rails app.

In these cases, you have a problem. The exception may occur in one of those two apps, the apps have the knowledge to properly handle or render the exception, but the exception tracker is somewhere higher in the stack level therefore it may not be able to see the error occurring (which is what was happening to us). Or, if you leave the error bubble up, then it will be tracked but who's going to rescue it? There will have to be some sort of new middleware that know how to deal with both errors from the App1 and App2 and potentially any other app that shares the same stack.

That's where `rack.exception` comes in. It's a sort of way of faking the response chain and forcing the exception notifier to track the error, even if the result of the `@app.call` at his Rack level did not trigger any exception but was a normal Rack array result.

I have the feeling, this is some sort of cargo culting. At some point, who first entered the marked of the exception logging, had to deal with this issue and decided to adopt a specific rack key to use as a "special" variable. `rack.exception` was born.

In order to maintain compatibility or simplify the transition, the new exception loggers that came after adopted the same convention. I suspect, many of these didn't include such feature originally, but then some user may have reported "an incompatibility" and they added it.

At this point, it's more clear to me that `rack.errors` and `rack.exceptions` serve different purposes and one doesn't exclude the other. Even if it's not a `rack` standard (yet?), I believe you did the right think to add support for it in https://github.com/lotus/controller/issues/134

I hope my message will also serve as a future reference if, one year from now, somebody will came across the same question and will search for it. :wink:

**Comment by jodosha** [comment]
@weppos Thank you for this detailed memo. It's really precious for us :+1:
