### ISSUE TITLE
Add a request method?

### ISSUE THREAD

**Issue by lasseebert** [lotus/controller#66]
When writing code inside an `Action`, I miss having access to a `request` method that returns a `Rack::Request`.

Someting like this:

```ruby
def request
  @request ||= Rack::Request.new(params.env)
end
```

I think this could be useful in general, and not just for me. Anyone have an oppinion on this?

And where should it be implemented if so? The most logical place IMO would be in `Params` as the `Params` class already knows about `env`.

- [x] Introduce a `#request` method which returns a `Lotus::Action::Request` instance
- [ ] ~~Add `#language` and `#encoding` to `Lotus::Action::Rack`.~~

**Comment by jodosha** [comment]
During the implementation of the remaining parts, I decided to postpone the support for them, and ship only @lasseebert work.

Encoding: This header is most used by web servers (such Nginx), to compress the response, after it was crafted by the application. It's rare and non slow to compress a request on the Ruby side.

Language: It turned out to be more complex. It involves locales as well, because browsers send mixed values like `en` which is a language and/or `en-US` which is a locale. All the research that the ruby-i18n team demonstrated that this is a larger topic. I'm keen to introduce i18n support here and in Lotus, but this isn't a priority. The result of my coding session is available at: https://github.com/lotus/controller/tree/language-support

Closing this, as it was implemented by #68 
/cc @joneslee85

**Comment by lasseebert** [comment]
I agree that it is non-trivial to parse the `Accept-Language` header in a way that is useful for a big majority of Lotus developers.

My specific case is trivial, and I'm happy that I now can use the Rack request helper method :)

**Comment by jodosha** [comment]
We're going to release a patch version with this fix on today.

http://lucaguidi.com

**Comment by jodosha** [comment]
@lasseebert FYI https://rubygems.org/gems/lotus-controller/versions/0.3.1
